# Generated by Django 6.0.7 on 2026-07-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_step', models.CharField(choices=[('started', 'Boshlandi'), ('waiting_name', 'Ism kutilmoqda'), ('waiting_phone', 'Telefon kutilmoqda'), ('completed', 'Yakunlangan')], default='started', max_length=20)),
                ('bot_state', models.CharField(blank=True, max_length=64, null=True)),
                ('bot_state_data', models.JSONField(blank=True, default=dict)),
                ('is_blocked_bot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram foydalanuvchi',
                'verbose_name_plural': 'Telegram foydalanuvchilar',
            },
        ),
    ]
