# Generated by Django 6.0.7 on 2026-07-16 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.PositiveSmallIntegerField(help_text='1, 2, 3 ... ketma-ketlik muhim', unique=True)),
                ('tier_name', models.CharField(help_text="Masalan: Boshlovchi, O'quvchi, Talaba", max_length=50)),
                ('gift_name', models.CharField(help_text='Masalan: Davron Turdiev Neyro boti', max_length=150)),
                ('gift_image', models.ImageField(blank=True, null=True, upload_to='gifts/')),
                ('claim_link', models.URLField(help_text="Sovg'ani olish uchun tashqi havola (anketa va h.k.)")),
                ('requires_form', models.BooleanField(default=False, help_text="True bo'lsa, havolaga telefon+telegram_id avtomatik qo'shib yuboriladi (bakal/kitob kabi jismoniy sovg'alar uchun)")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Oylik sovg'a",
                'verbose_name_plural': "Oylik sovg'alar",
                'ordering': ['month_number'],
            },
        ),
        migrations.CreateModel(
            name='UserGiftProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak_months', models.PositiveSmallIntegerField(default=0)),
                ('highest_streak_months', models.PositiveSmallIntegerField(default=0)),
                ('streak_broken_count', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gift_progress', to='users.telegramuser')),
            ],
            options={
                'verbose_name': "Sovg'a jarayoni",
                'verbose_name_plural': "Sovg'a jarayonlari",
            },
        ),
        migrations.CreateModel(
            name='UserGiftClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('gift_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='gifts.giftmonth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_claims', to='users.telegramuser')),
            ],
            options={
                'verbose_name': "Sovg'a olingani",
                'verbose_name_plural': "Sovg'a olinganlar",
                'unique_together': {('user', 'gift_month')},
            },
        ),
    ]
