# Generated by Django 5.1.15 on 2026-07-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftmonth',
            name='requires_form',
        ),
        migrations.AlterField(
            model_name='giftmonth',
            name='claim_link',
            field=models.URLField(help_text="Sovg'ani olish uchun tashqi havola"),
        ),
    ]
