# Generated by Django 6.0.7 on 2026-07-16 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Faqat admin panel uchun, mijozga ko'rinmaydi", max_length=150)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='broadcasts/')),
                ('target_type', models.CharField(choices=[('all', 'Barcha foydalanuvchilar'), ('active_subscribers', 'Faol obunachilar'), ('expired_subscribers', 'Muddati tugaganlar'), ('specific_plan', 'Muayyan tarif obunachilari'), ('custom_list', "Qo'lda tanlangan foydalanuvchilar")], default='all', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('queued', "Navbatga qo'yilgan"), ('sending', 'Yuborilmoqda'), ('sent', 'Yuborildi'), ('failed', 'Xatolik')], default='draft', max_length=20)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('custom_users', models.ManyToManyField(blank=True, related_name='custom_broadcasts', to='users.telegramuser')),
                ('target_plan', models.ForeignKey(blank=True, help_text="Faqat target_type=specific_plan bo'lsa ishlatiladi", null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, max_length=255, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='broadcast.broadcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.telegramuser')),
            ],
            options={
                'unique_together': {('broadcast', 'user')},
            },
        ),
    ]
