# Generated by Django 5.1.15 on 2026-07-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0002_broadcast_button_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='is_video_note',
            field=models.BooleanField(default=False, help_text="Yoqilgan bo'lsa, video oddiy (to'rtburchak) emas, balki Telegramning dumaloq video xabari (video note) sifatida yuboriladi"),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text="Belgilansa, e'lon shu sana/vaqtda avtomatik yuboriladi (bo'sh bo'lsa — qo'lda yuborish kerak)", null=True),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='video',
            field=models.FileField(blank=True, help_text="Ixtiyoriy video. 'Dumaloq video xabar' belgilansa, Telegram'da doira shaklida (video note) yuboriladi — bunda kvadrat (1:1) va 60 soniyagacha bo'lishi tavsiya etiladi.", null=True, upload_to='broadcasts/videos/'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('scheduled', 'Rejalashtirilgan'), ('queued', "Navbatga qo'yilgan"), ('sending', 'Yuborilmoqda'), ('sent', 'Yuborildi'), ('failed', 'Xatolik')], default='draft', max_length=20),
        ),
    ]
