# Generated by Django 6.0.7 on 2026-07-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('private_channel', "Yopiq kanalga qo'shilish havolasi"), ('help', 'Yordam havolasi'), ('community_chat', 'Umumiy chat havolasi'), ('offer_document', 'Oferta hujjati havolasi')], max_length=30, unique=True)),
                ('url', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot havolasi',
                'verbose_name_plural': 'Bot havolalari',
            },
        ),
        migrations.CreateModel(
            name='BotMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=150)),
                ('video', models.FileField(blank=True, null=True, upload_to='bot_media/')),
                ('video_url', models.URLField(blank=True, help_text="Fayl o'rniga tashqi/Telegram file_id ham bo'lishi mumkin", null=True)),
                ('telegram_file_id', models.CharField(blank=True, help_text='Qayta yuklamaslik uchun keshlangan file_id', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Bot media',
                'verbose_name_plural': 'Bot medialari',
            },
        ),
        migrations.CreateModel(
            name='BotText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(help_text='Admin panelda tanish uchun nom', max_length=150)),
                ('text', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot matni',
                'verbose_name_plural': 'Bot matnlari',
            },
        ),
    ]
