# Generated by Django 5.1.15 on 2026-07-18 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_static_bot_texts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('ask_name', "Ismni so'rash"), ('ask_phone', "Telefon so'rash"), ('phone_accepted', 'Telefon qabul qilindi'), ('offer_intro', 'Akademiya taklifi'), ('tariff_select', 'Tarif tanlash'), ('payment_method_select', "To'lov usulini tanlash"), ('main_menu', 'Asosiy menyu'), ('subscription_status', 'Obuna holati'), ('card_change_intro', 'Karta almashtirish'), ('renewal_reminder_3d', 'Eslatma — 3 kun qoldi'), ('renewal_reminder_2d', 'Eslatma — 2 kun qoldi'), ('renewal_reminder_1d', 'Eslatma — 1 kun qoldi'), ('renewal_reminder_1d_sms', 'SMS eslatma — 1 kun qoldi'), ('renewal_processing_alert', 'Ishlanmoqda (alert)'), ('renewal_fail_1', "To'lov yechilmadi — 1-urinish"), ('renewal_fail_2', "To'lov yechilmadi — 2-urinish"), ('renewal_fail_3', "To'lov yechilmadi — 3-urinish"), ('renewal_fail_4', "To'lov yechilmadi — 4-urinish"), ('renewal_card_expired', "Karta muddati o'tgan"), ('renewal_card_change_intro', 'Karta almashtirish (kaskad ichida)'), ('renewal_success', "To'lov muvaffaqiyatli"), ('renewal_cancelled', "Obuna to'xtatildi")], help_text='Qaysi statik bot xabari (kod nuqtasi)', unique=True)),
                ('group', models.CharField(choices=[('onboarding', "Ro'yxatdan o'tish"), ('payment', "Taklif va to'lov"), ('main_menu', 'Asosiy menyu va obuna holati'), ('renewal_reminders', "Avto-to'lov — eslatmalar"), ('renewal_fail_cascade', "Avto-to'lov — muvaffaqiyatsiz urinishlar")], db_index=True, max_length=30)),
                ('title', models.CharField(help_text="Faqat admin panelda ko'rinadi, mijozga yuborilmaydi", max_length=150)),
                ('text', models.TextField(help_text='Mijozga yuboriladigan joriy matn')),
                ('default_text', models.TextField(help_text="Zavod sozlamasi (kod ichidagi asl matn) — 'Asliga qaytarish' uchun")),
                ('placeholders', models.JSONField(blank=True, default=list, help_text="Ushbu matnda ishlatilishi mumkin bo'lgan {placeholder} nomlari (avtomatik aniqlangan, faqat ma'lumot uchun)")),
                ('is_locked', models.BooleanField(default=False, help_text="Yoqilgan bo'lsa, faqat superuser tahrirlay oladi (masalan oferta/rozilik matni bor xabarlar)")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bot xabari (tahrirlanadigan)',
                'verbose_name_plural': 'Bot xabarlari (tahrirlanadigan)',
                'ordering': ['group', 'slug'],
            },
        ),
    ]
