# Generated by Django 5.1.15 on 2026-07-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_botmedia_media_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_chat_id', models.BigIntegerField(blank=True, help_text="Yopiq kanalning raqamli chat ID'si (masalan -1001234567890). Bo'sh bo'lsa, avtomatik chiqarib yuborish ishlamaydi.", null=True)),
                ('auto_kick_on_expiry', models.BooleanField(default=True, help_text='Obuna muddati tugagan/bekor qilingan foydalanuvchi avtomatik ravishda kanaldan chiqarib yuborilsinmi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kanal sozlamalari',
                'verbose_name_plural': 'Kanal sozlamalari',
            },
        ),
        migrations.AlterField(
            model_name='botmessagetemplate',
            name='group',
            field=models.CharField(choices=[('onboarding', "Ro'yxatdan o'tish"), ('payment', "Taklif va to'lov"), ('main_menu', 'Asosiy menyu va obuna holati'), ('renewal_reminders', "Avto-to'lov — eslatmalar"), ('renewal_fail_cascade', "Avto-to'lov — muvaffaqiyatsiz urinishlar"), ('admission', 'Qabul yopiq xabari')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='botmessagetemplate',
            name='slug',
            field=models.SlugField(choices=[('ask_name', "Ismni so'rash"), ('ask_phone', "Telefon so'rash"), ('phone_accepted', 'Telefon qabul qilindi'), ('offer_intro', 'Akademiya taklifi'), ('tariff_select', 'Tarif tanlash'), ('payment_method_select', "To'lov usulini tanlash"), ('main_menu', 'Asosiy menyu'), ('subscription_status', 'Obuna holati'), ('card_change_intro', 'Karta almashtirish'), ('renewal_reminder_3d', 'Eslatma — 3 kun qoldi'), ('renewal_reminder_2d', 'Eslatma — 2 kun qoldi'), ('renewal_reminder_1d', 'Eslatma — 1 kun qoldi'), ('renewal_reminder_1d_sms', 'SMS eslatma — 1 kun qoldi'), ('renewal_processing_alert', 'Ishlanmoqda (alert)'), ('renewal_fail_1', "To'lov yechilmadi — 1-urinish"), ('renewal_fail_2', "To'lov yechilmadi — 2-urinish"), ('renewal_fail_3', "To'lov yechilmadi — 3-urinish"), ('renewal_fail_4', "To'lov yechilmadi — 4-urinish"), ('renewal_card_expired', "Karta muddati o'tgan"), ('renewal_card_change_intro', 'Karta almashtirish (kaskad ichida)'), ('renewal_success', "To'lov muvaffaqiyatli"), ('renewal_cancelled', "Obuna to'xtatildi"), ('admission_closed', 'Qabul yopiq')], help_text='Qaysi statik bot xabari (kod nuqtasi)', unique=True),
        ),
    ]
