# Generated by Django 5.1.15 on 2026-07-24 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_channelsettings_alter_botmessagetemplate_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessagetemplate',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Faqat trigger_event='attempt' bo'lsa: nechinchi muvaffaqiyatsiz urinishda yuborilsin.", null=True),
        ),
        migrations.AddField(
            model_name='botmessagetemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text="O'chirilgan bo'lsa, bu xabar yuborilmaydi (o'chirib tashlamasdan vaqtincha to'xtatish uchun)."),
        ),
        migrations.AddField(
            model_name='botmessagetemplate',
            name='step_type',
            field=models.CharField(choices=[('core', "Tizim bosqichi (kod bilan bog'langan)"), ('custom', "Qo'shimcha xabar (admin qo'shgan)")], db_index=True, default='core', help_text="CORE — kod bilan bog'langan, o'chirilmaydi. CUSTOM — admin qo'shgan qo'shimcha xabar.", max_length=10),
        ),
        migrations.AddField(
            model_name='botmessagetemplate',
            name='trigger_event',
            field=models.CharField(blank=True, choices=[('attempt', 'Muayyan urinish raqami'), ('card_expired', "Karta muddati o'tgan"), ('card_change_requested', "Kaskad ichida 'Kartani almashtirish' bosilganda"), ('success', "To'lov muvaffaqiyatli bo'ldi"), ('cancelled', 'Obuna bekor qilindi'), ('in_progress', "To'lov ishlanmoqda (alert)")], help_text="Faqat 'Avto-to'lov — muvaffaqiyatsiz urinishlar' toifasida ishlatiladi: bu qadam qaysi haqiqiy hodisada ishga tushishi.", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='botmedia',
            name='slug',
            field=models.SlugField(help_text='Qaysi bot xabariga (BotMessageTemplate.slug — CORE yoki CUSTOM) biriktirilgan', unique=True),
        ),
        migrations.AlterField(
            model_name='botmessagetemplate',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text="Admin konstruktoridagi kartochka tartibi (guruh ichida, yoki kaskad guruhida — bitta urinish/hodisa ichida bir nechta xabar bo'lsa, ular orasidagi tartib)."),
        ),
        migrations.AlterField(
            model_name='botmessagetemplate',
            name='slug',
            field=models.SlugField(help_text='CORE qatorlar uchun — qaysi statik bot xabari (kod nuqtasi). CUSTOM qatorlar uchun — avtomatik generatsiya qilinadi.', unique=True),
        ),
        migrations.CreateModel(
            name='FunnelCategorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('onboarding', "Ro'yxatdan o'tish"), ('payment', "Taklif va to'lov"), ('main_menu', 'Asosiy menyu va obuna holati'), ('renewal_reminders', "Avto-to'lov — eslatmalar"), ('renewal_fail_cascade', "Avto-to'lov — muvaffaqiyatsiz urinishlar"), ('admission', 'Qabul yopiq xabari')], max_length=30, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voronka kategoriya tartibi',
                'verbose_name_plural': 'Voronka kategoriya tartiblari',
                'ordering': ['sort_order'],
            },
        ),
    ]
