# Generated by Django 5.1.15 on 2026-07-19 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Masalan: VSL1 — havolada ?start=VSL1 ko'rinishida ishlatiladi", unique=True)),
                ('label', models.CharField(help_text='Ichki nom, masalan: YouTube — VSL 1-video', max_length=150)),
                ('is_active', models.BooleanField(default=True, help_text="O'chirilsa, bu havola orqali yangi foydalanuvchi ro'yxatdan o'ta olmaydi (qabul umumiy holatiga bo'ysunadi)")),
                ('leads_count', models.PositiveIntegerField(default=0, help_text='Shu havola orqali botga kirgan yangi (unikal) foydalanuvchilar soni')),
                ('sales_count', models.PositiveIntegerField(default=0, help_text="Shu havola orqali kelib birinchi marta to'lov qilganlar soni")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Referal havola',
                'verbose_name_plural': 'Referal havolalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True, help_text='Yangi foydalanuvchilar uchun qabul umuman ochiqmi')),
                ('allow_referral_when_closed', models.BooleanField(default=True, help_text="Qabul yopiq bo'lsa ham, faol referal havolalar orqali kirganlar uchun ochiq qolsinmi")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Qabul sozlamalari',
                'verbose_name_plural': 'Qabul sozlamalari',
            },
        ),
    ]
