# Generated by Django 6.0.7 on 2026-07-16 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_days_before', models.CharField(default='3,2,1', help_text="Vergul bilan ajratilgan, to'lov sanasidan necha kun oldin eslatma yuborilsin. Masalan: 3,2,1", max_length=50)),
                ('sms_reminder_day_before', models.PositiveSmallIntegerField(default=1, help_text="Necha kun qolganda SMS yuborilsin (0 = SMS o'chirilgan)")),
                ('retry_wait_hours_stage_1', models.PositiveSmallIntegerField(default=24)),
                ('retry_wait_hours_stage_2', models.PositiveSmallIntegerField(default=24)),
                ('retry_wait_hours_stage_3', models.PositiveSmallIntegerField(default=18)),
                ('retry_wait_hours_stage_4', models.PositiveSmallIntegerField(default=6)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5, help_text="Jami nechta urinishdan keyin obuna butunlay to'xtatilsin")),
            ],
            options={
                'verbose_name': "Avto to'lov sozlamalari",
                'verbose_name_plural': "Avto to'lov sozlamalari",
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Masalan: 1 oylik obuna', max_length=100)),
                ('duration_months', models.PositiveSmallIntegerField(help_text="Necha oyga obuna (to'lov davriyligi ham shu)")),
                ('price_uzs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_usd', models.DecimalField(decimal_places=2, help_text='Chet eldan (Tribute) narxi', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Tugmalar tartibi')),
            ],
            options={
                'verbose_name': 'Obuna tarifi',
                'verbose_name_plural': 'Obuna tariflari',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masked_pan', models.CharField(help_text="561468******7403 ko'rinishida", max_length=25)),
                ('payme_card_token', models.CharField(help_text='Payme create-card tokeni (maxfiy, faqat backend ishlatadi)', max_length=255)),
                ('is_primary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='users.telegramuser')),
            ],
            options={
                'verbose_name': "Bog'langan karta",
                'verbose_name_plural': "Bog'langan kartalar",
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', "To'lov kutilmoqda"), ('active', 'Faol'), ('cancelled', "Avto to'lov bekor qilingan (muddat oxirigacha faol)"), ('expired', 'Tugagan')], default='pending', max_length=20)),
                ('provider', models.CharField(choices=[('payme', 'Payme (Uzcard/Humo)'), ('tribute', 'Tribute (chet eldan)')], max_length=20)),
                ('tribute_external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('next_payment_date', models.DateField(blank=True, db_index=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.paymentcard')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='users.telegramuser')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Obuna',
                'verbose_name_plural': 'Obunalar',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('provider', models.CharField(choices=[('payme', 'Payme (Uzcard/Humo)'), ('tribute', 'Tribute (chet eldan)')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Muvaffaqiyatli'), ('failed', 'Muvaffaqiyatsiz'), ('pending', 'Kutilmoqda')], default='pending', max_length=20)),
                ('external_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_recurring_charge', models.BooleanField(default=False, help_text="False = mijoz o'zi to'lagan birinchi to'lov")),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionRenewalCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(help_text="Ushbu billing davri uchun to'lov sanasi (Subscription.next_payment_date qiymati shu kunga teng bo'lganda yaratiladi)")),
                ('status', models.CharField(choices=[('scheduled', 'Navbatda'), ('in_progress', 'Yechilmoqda (qulflangan)'), ('awaiting_user', "Mijoz kutilmoqda ('Davom etish')"), ('awaiting_card_update', 'Karta yangilanishi kutilmoqda'), ('succeeded', 'Muvaffaqiyatli yakunlandi'), ('cancelled', "Obuna to'xtatildi")], default='scheduled', max_length=25)),
                ('attempt_number', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, help_text="IN_PROGRESS holatiga o'tgan vaqt — stale-lock aniqlash uchun", null=True)),
                ('last_result', models.CharField(blank=True, max_length=30, null=True)),
                ('last_error_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_cycles', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'Obuna yangilash jarayoni',
                'verbose_name_plural': 'Obuna yangilash jarayonlari',
                'unique_together': {('subscription', 'due_date')},
            },
        ),
        migrations.CreateModel(
            name='PendingCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_uuid', models.UUIDField(unique=True)),
                ('provider', models.CharField(choices=[('payme', 'Payme (Uzcard/Humo)'), ('tribute', 'Tribute (chet eldan)')], max_length=20)),
                ('purpose', models.CharField(choices=[('new_subscription', 'Yangi obuna'), ('card_change', 'Kartani almashtirish (oddiy)'), ('renewal_card_update', "Kartani almashtirish (to'lov kaskadi ichida)")], default='new_subscription', max_length=25)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_checkouts', to='users.telegramuser')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplan')),
                ('renewal_cycle', models.ForeignKey(blank=True, help_text="Faqat purpose=renewal_card_update bo'lganda to'ldiriladi — karta yangilangach shu cycle qayta urinadi", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_update_checkouts', to='subscriptions.subscriptionrenewalcycle')),
            ],
            options={
                'verbose_name': "To'lov jarayoni (vaqtinchalik)",
                'verbose_name_plural': "To'lov jarayonlari (vaqtinchalik)",
            },
        ),
        migrations.CreateModel(
            name='PaymentReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('reminder_type', models.CharField(choices=[('days_before', 'N kun oldin (bot)'), ('sms_day_before', 'SMS eslatma')], max_length=20)),
                ('days_before', models.PositiveSmallIntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'Eslatma jurnali',
                'verbose_name_plural': 'Eslatmalar jurnali',
                'unique_together': {('subscription', 'due_date', 'reminder_type', 'days_before')},
            },
        ),
        migrations.CreateModel(
            name='RenewalAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('result', models.CharField(max_length=30)),
                ('error_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('payme_order_id', models.CharField(help_text='cycle_id+attempt_number asosida — idempotentlik uchun', max_length=100)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='subscriptions.subscriptionrenewalcycle')),
            ],
            options={
                'verbose_name': "To'lov urinishi",
                'verbose_name_plural': "To'lov urinishlari",
                'ordering': ['attempt_number'],
                'unique_together': {('cycle', 'attempt_number')},
            },
        ),
    ]
