# Generated by Django 5.1.15 on 2026-07-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_pendingcheckout_card_form_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewalattempt',
            name='payme_receipt_id',
            field=models.CharField(blank=True, help_text="Payme receipts.create javobidagi chek ID'si. Agar shu urinish 'error' bilan tugagan bo'lsa (masalan receipts.pay javobi tarmoq uzilishi sabab yetib kelmagan bo'lsa), keyingi urinishdan oldin receipts.check shu ID orqali tekshiriladi — pul haqiqatda allaqachon yechilgan bo'lsa, ikkinchi marta yechilmasligi uchun.", max_length=100, null=True),
        ),
    ]
