# Generated by Django 5.1.15 on 2026-07-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_renewalattempt_payme_receipt_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('external_transaction_id', None), _negated=True), models.Q(('external_transaction_id', ''), _negated=True)), fields=('provider', 'external_transaction_id'), name='unique_provider_external_transaction_id'),
        ),
    ]
