# Generated by Django 5.1.15 on 2026-07-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_payment_unique_provider_external_transaction_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RenewalSettings',
        ),
    ]
