# Generated by Django 5.1.15 on 2026-07-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_renewalsettings_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='locked_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Xuddi shu mantiq — chet eldan (Tribute) narxi uchun.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='locked_price_uzs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Mijoz shu obunani (yoki qayta obunani) sotib olgan paytdagi Payme narxi — 'muzlatilgan' narx. Keyingi barcha avto to'lovlar (kaskad) shu qiymatdan yechiladi, hatto admin panelda tarif narxi (`SubscriptionPlan.price_uzs`) keyinchalik oshirilgan/tushirilgan bo'lsa ham — mijoz obuna shartlarini buzmaguncha (bekor qilib/muddati tugab qayta sotib olguncha) shu narxda qolaveradi. Mijoz qaytadan (yangidan) sotib olganda bu qiymat joriy narx bilan qayta yozib qo'yiladi. Bo'sh (`null`) bo'lsa — bu maydon qo'shilishidan OLDIN yaratilgan eski obuna, xavfsizlik uchun joriy plan narxiga tushiladi.", max_digits=12, null=True),
        ),
    ]
