# Generated by Django 5.1.15 on 2026-07-19 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_subscription_locked_price_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewalsettings',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=5, help_text="Jami nechta urinishdan keyin obuna avtomatik bekor qilinsin (1 dastlabki + qayta urinishlar). Amalda 4 tadan ortiq qayta urinish uchun alohida matn yo'q — 4-dan keyingi barcha urinishlar '4-urinish' matni bilan yuboriladi.", validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
