# Generated by Django 5.1.15 on 2026-07-24 10:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_alter_renewalsettings_max_attempts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renewalsettings',
            name='max_attempts',
        ),
        migrations.RemoveField(
            model_name='renewalsettings',
            name='retry_wait_hours_stage_1',
        ),
        migrations.RemoveField(
            model_name='renewalsettings',
            name='retry_wait_hours_stage_2',
        ),
        migrations.RemoveField(
            model_name='renewalsettings',
            name='retry_wait_hours_stage_3',
        ),
        migrations.RemoveField(
            model_name='renewalsettings',
            name='retry_wait_hours_stage_4',
        ),
        migrations.CreateModel(
            name='RenewalRetryStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(help_text="Ushbu urinish (masalan 1, 2, 3...) muvaffaqiyatsiz bo'lsa, keyingisigacha necha soat kutilishi haqida.", unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('wait_hours', models.PositiveSmallIntegerField(help_text="Shu urinish muvaffaqiyatsiz bo'lsa, keyingi urinishgacha necha soat kutilsin.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Avto-to'lov qayta urinish bosqichi",
                'verbose_name_plural': "Avto-to'lov qayta urinish bosqichlari",
                'ordering': ['attempt_number'],
            },
        ),
    ]
