# Generated by Django 6.0.7 on 2026-07-16 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('external_link', models.URLField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Jamiyat kategoriyasi',
                'verbose_name_plural': 'Jamiyat kategoriyalari',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cover_image', models.ImageField(upload_to='content_categories/')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kontent kategoriyasi',
                'verbose_name_plural': 'Kontent kategoriyalari',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_link', models.URLField(help_text='Bosilganda mijoz shu havolaga uloqtiriladi')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiallar',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='CommunityContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='community/')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.communitycategory')),
            ],
            options={
                'verbose_name': 'Jamiyat elementi',
                'verbose_name_plural': 'Jamiyat elementlari',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='content_covers/')),
                ('description', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('file', 'Fayl')], default='video', max_length=10)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='content_media/')),
                ('media_url', models.URLField(blank=True, help_text="Agar tashqi (masalan YouTube/CDN) havola bo'lsa", null=True)),
                ('published_date', models.DateField()),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='content.contentcategory')),
            ],
            options={
                'verbose_name': 'Kontent',
                'verbose_name_plural': 'Kontentlar',
                'ordering': ['position', '-published_date'],
            },
        ),
        migrations.CreateModel(
            name='ContentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='content.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_likes', to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'Kontent like',
                'verbose_name_plural': 'Kontent likelar',
                'unique_together': {('user', 'content')},
            },
        ),
    ]
