# Generated by Django 5.1.15 on 2026-07-18 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcategory',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Agar to'ldirilsa — bu kategoriya boshqa kategoriyaning ICHKI kategoriyasi hisoblanadi", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.contentcategory'),
        ),
    ]
